version: '3.9'
services:
  ssh.cyrhades.com:
    build: ssh
  webssh.cyrhades.com:
    build: webssh
    ports:
    - "80:8888"
  build-your-own-team.cyrhades.com:
    image: anssi/fcsc2019-pwn-build-your-own-team:latest
    ports:
      - "4000:4000"
